### ISSUE TITLE
对于生成2D的PSF有相应的代码吗

### ISSUE THREAD

**Issue by 464hee** [TristaZeng/ZS-DeconvNet#10]
感谢你们团队的突出工作。
我看到示例训练数据中，2D data\Microtubule\PSF\psf_emLambda525_dxy0.0313_NA1.3.tif
大小是(257, 257)，可以新增加生成2D-PSF脚本吗？

**Comment by TristaZeng** [comment]
可以见Python_MATLAB_Codes/data_augment_recorrupt_matlab/GenData4ZS-DeconvNet/create_PSF.m

**Comment by 464hee** [comment]
好的
