### ISSUE TITLE
Questions about the determination of β2 parameters

### ISSUE THREAD

**Issue by Albert22dai** [TristaZeng/ZS-DeconvNet#12]
Thanks to the author, the article is very helpful in our work! In practice, the β2 parameter is a bit unclear for me.
β2 is dependent to the camera and can be estimated from the sample-free region of the image itself or precalibrated following standard protocols.
1, How to determine β2 according to the standard protocols? 
2, Is the range (5-15) in the code about β2 generic, in some images the estimated β2 parameter based on image (16bit) is sometimes very large(e4) and the outcome is not good.

**Comment by TristaZeng** [comment]
β2 is the variance of the Gaussian noise from the camera, so the variance of the "blank" region of the image is a good estimation. The estimation and re-corruption should be done on raw data, not normalized data. If β2 is not accurate, the most likely reason is that the extraction of "blank" region is wrong. You can adjust `thresh` (line 25) in `DataAugmFor2D` based on `mask`.

**Comment by Albert22dai** [comment]
Thanks for your reply, I tried adjusting thresh to ensure it can accurately extract the "blank" region. There is a strange phenomenon. When estimate_beta2 is used, β2 will be larger, and the training output is not as good as the results obtained by randomly selecting β2 training in [10,15].
I noticed that there is an evaluation of β2 in the supplementary material. Why is the interval [1, 25] selected here? According to experience, the β2 estimated for the blank region of the noisy WF input should be relatively large.
![image](https://github.com/user-attachments/assets/4b431b4b-2469-4444-894c-d9048af689a0)

**Comment by TristaZeng** [comment]
We used [1, 25] because we actually know in this simulation that our background variance is 12.25. Did you perform the estimation on raw data captured directly from microscopy?

**Comment by Albert22dai** [comment]
We created the GT(max_value=4e+4) by enlarging the exposure time to acquire the high-SNR data, and then add Gaussian noise (sigma=1000) to simulate the noisy images collected as network input. We estimate the parameter β2 directly on the simulated noisy image (1e+6)

**Comment by TristaZeng** [comment]
I don't see explicitly any bugs in your process, but you can try making the maximum signal value in your GT smaller, e.g., 50, and then add smaller sigma.

**Comment by Albert22dai** [comment]
Thanks. I noticed in the article that the method of eliminating pseudo-edges by zero-padding at image edges is used. How is the size of the zero-padding determined, especially for 3D data?

**Comment by TristaZeng** [comment]
It's just determined empirically. You can refer to the default values, which worked for us.
